#!/usr/bin/env python3
"""Visual Storyboard Synthesizer for ChloeOS Maestro.

Ingests `music_opinion.json` (generated by AGY CLI) along with music grid data
and produces a curated, director-ready `storyboard.json` ready for Steve's
review and approval in the Dashboard GUI.

Usage:
    python storyboard_generator.py songs/silicon_heartbeat [--target-shots 21]
"""

import argparse
import json
import sys
from pathlib import Path


def generate_storyboard(song_dir: Path, target_shots: int = 21) -> dict:
    song_dir = Path(song_dir).resolve()

    opinion_file = song_dir / "music_opinion.json"
    if not opinion_file.exists():
        sys.exit(f"Error: music_opinion.json not found in {song_dir}. Run agy_music_critic.py first.")

    opinion = json.loads(opinion_file.read_text(encoding="utf-8"))

    # Load music analysis or fallback
    music_file = next(song_dir.glob("*.music.json"), None)
    bpm = 120.0
    duration = 180.0
    if music_file and music_file.exists():
        try:
            m_data = json.loads(music_file.read_text(encoding="utf-8"))
            bpm = m_data.get("bpm", 120.0) or 120.0
            duration = m_data.get("duration", 180.0) or 180.0
        except Exception:
            pass

    energy_sections = opinion.get("energy_sections", [])
    if not energy_sections:
        sys.exit("Error: No energy_sections found in music_opinion.json.")

    print(f"[Storyboard Generator] Synthesizing storyboard for {opinion.get('song_title', song_dir.name)}")
    print(f"  BPM: {bpm:.1f} | Duration: {duration:.3f}s | Sections: {len(energy_sections)}")

    # Check if a v2 blueprint/shotlist already exists to preserve established good scenes
    existing_shots_map = {}
    for candidate in [song_dir / "shotlist_v2.json", song_dir / "blueprint_v2.json", song_dir / "shotlist.json"]:
        if candidate.exists():
            try:
                raw = json.loads(candidate.read_text(encoding="utf-8"))
                for s in raw.get("shots", []):
                    existing_shots_map[s.get("shot")] = s
            except Exception:
                pass
            if existing_shots_map:
                break

    # Build shots distributed across sections
    total_shots = target_shots
    shots = []
    
    # Calculate time slots
    step = duration / total_shots
    current_time = 0.0

    for i in range(1, total_shots + 1):
        t_start = round(current_time, 2)
        t_end = round(min(duration, current_time + step), 2)
        dur = round(t_end - t_start, 2)
        current_time = t_end

        # Match section
        sec = next((s for s in energy_sections if s["t_start"] <= t_start <= s["t_end"]), energy_sections[-1])

        # Preserve existing shot if curated, else synthesize from AGY opinion
        if i in existing_shots_map:
            prev = existing_shots_map[i]
            shot_entry = {
                "shot": i,
                "t_start": t_start,
                "duration": dur,
                "seconds": dur,
                "section": sec.get("section", "Scene"),
                "camera": prev.get("camera", sec.get("cinematography", "Cinematic Tracking")),
                "scene": prev.get("scene", sec.get("narrative_action", "Odyssey Narrative")),
                "prompt": prev.get("prompt", ""),
                "color_palette": sec.get("color_palette", "Teal and Amber"),
                "approved": False,
                "anchor_image_path": prev.get("anchor_image_path", ""),
                "clip_path": prev.get("clip_path", "")
            }
        else:
            # Construct fresh prompt aligned with AGY directives
            prompt = (
                f"{sec.get('cinematography', 'Cinematic tracking shot')}. "
                f"{sec.get('narrative_action', 'A sleek white cyber-interceptor maneuvers at high speed')}. "
                f"{sec.get('lighting_and_atmosphere', 'Atmospheric volumetric lighting')}. "
                f"Color palette: {sec.get('color_palette', 'wet asphalt and cyan neon')}. "
                f"35mm film grain, photorealistic 8k, masterpiece cinematic."
            )
            shot_entry = {
                "shot": i,
                "t_start": t_start,
                "duration": dur,
                "seconds": dur,
                "section": sec.get("section", "Scene"),
                "camera": sec.get("cinematography", "Cinematic Tracking"),
                "scene": sec.get("narrative_action", f"Sequence {i}"),
                "prompt": prompt,
                "color_palette": sec.get("color_palette", "Cyan & Noir"),
                "approved": False,
                "anchor_image_path": "",
                "clip_path": ""
            }

        shots.append(shot_entry)

    storyboard = {
        "title": opinion.get("song_title", song_dir.name),
        "duration": duration,
        "bpm": bpm,
        "total_shots": len(shots),
        "status": "pending_curator_approval",
        "approved": False,
        "agy_overall_mood": opinion.get("overall_mood", ""),
        "director_summary": opinion.get("director_summary", ""),
        "directives": opinion.get("visual_storyboard_directives", []),
        "shots": shots
    }

    out_file = song_dir / "storyboard.json"
    out_file.write_text(json.dumps(storyboard, indent=2), encoding="utf-8")
    print(f"[OK] Visual Storyboard saved to {out_file.name} ({len(shots)} shots).")
    print(f"     Status: pending_curator_approval (Launch Dashboard GUI to curate and approve).")

    return storyboard


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("song_dir", help="Path to song directory")
    parser.add_argument("--target-shots", type=int, default=21, help="Target number of shots")
    args = parser.parse_args()

    generate_storyboard(Path(args.song_dir), target_shots=args.target_shots)


if __name__ == "__main__":
    main()
